#source 'https://github.com/CocoaPods/Specs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '12.0'
project 'DmaIRIS_SDK_IOS'

inhibit_all_warnings!
use_frameworks!
target 'DmaIRIS_SDK_IOS_Example' do
  pod 'UptickProtocolIRISnet', :path => '../'
#  pod 'gRPC-Swift', '1.0.0-alpha.20'

  target 'DmaIRIS_SDK_IOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
